Update setter scripts

diff --git a/overlay/usr/local/bin/jdownloaderset b/overlay/usr/local/bin/jdownloaderset
--- a/overlay/usr/local/bin/jdownloaderset
+++ b/overlay/usr/local/bin/jdownloaderset
@@ -14,19 +14,23 @@ set_json_value()
 give_message()
 {
     if [ $? -eq 0 ] ; then
-        echo "Changing $CONFIG_FILE"
+        echo "Changing $1 in $CONFIG_FILE"
     else
-        echo "Error updating $CONFIG_FILE">2 ; exit 1
+        echo "Error updating $1 in $CONFIG_FILE">&2 ; exit 1
     fi
 }
 
 case $1 in
     email) set_json_value $1 $2
-           give_message
+           give_message $1
            ;;
     password) set_json_value $1 $2
-              give_message
+              give_message $1
               ;;
+
+    devicename) set_json_value $1 $2
+                give_message $1
+                ;;
     *) echo "Unknown option">&2 ; exit 1
             ;;
 esac
